///////////////////////////////////////////////////////////
//  ConversionHandler.cs
//  Implementation of the Class ConversionHandler
//  Generated by Enterprise Architect
//  Created on:      19-Mar-2019 7:18:07 PM
///////////////////////////////////////////////////////////

namespace LengthConversionProgram
{
    public abstract class ConversionHandler
    {
        protected ConversionHandler successor;
        public string DecoratedOutput;

        public abstract void HandleConversion(ConversionRequest currentRequest);

        public void SetSuccessor(ConversionHandler unit)
        {
            this.successor = unit;
        }
    }
}