///////////////////////////////////////////////////////////
//  ExpDecorator.cs
//  Implementation of the Class ExpDecorator
//  Generated by Enterprise Architect
//  Created on:      20-Mar-2019 9:59:45 AM
///////////////////////////////////////////////////////////

using System;

namespace LengthConversionProgram
{
    public class ExpDecorator : HandlerDecorator
    {
        public ExpDecorator(ConversionHandler conversionHandler)
        {
            this.conversionHandler = conversionHandler;
            this.conversionHandler.DecoratedOutput = 
                (Double.Parse(conversionHandler.DecoratedOutput)).ToString("e");
        }
    }
}