///////////////////////////////////////////////////////////
//  ExpDecorator.cs
//  Implementation of the Class ExpDecorator
//  Generated by Enterprise Architect
//  Created on:      20-Mar-2019 9:59:45 AM
///////////////////////////////////////////////////////////

using System;

namespace LengthConversionProgram
{
    public class ExpDecorator : HandlerDecorator
    {
        public ExpDecorator(ConversionHandler conversionHandler)
        {
            this.DecoratedOutput = conversionHandler.DecoratedOutput;
        }

        public override void HandleConversion(string unitRequested, ConversionRequest currentRequest)
        {
            this.DecoratedOutput = (Double.Parse(this.DecoratedOutput)).ToString("e");
        }
    }
}