///////////////////////////////////////////////////////////
//  HanlderDecorator.cs
//  Implementation of the Class HanlderDecorator
//  Generated by Enterprise Architect
//  Created on:      20-Mar-2019 9:59:42 AM
///////////////////////////////////////////////////////////


namespace LengthConversionProgram
{

    public abstract class HandlerDecorator : ConversionHandler
    {
        /*
         * C# does not allow double abstract functions. 
         * Decorators implement this function from ConversionHandler.
         */
        //public abstract void HandleConversion(string unitRequested, ConversionRequest currentRequest);
    }
}