///////////////////////////////////////////////////////////
//  HanlderDecorator.cs
//  Implementation of the Class HanlderDecorator
//  Generated by Enterprise Architect
//  Created on:      20-Mar-2019 9:59:42 AM
///////////////////////////////////////////////////////////


namespace LengthConversionProgram
{

    public class HandlerDecorator
    {
        public ConversionHandler conversionHandler { get; set; }

        public HandlerDecorator(ConversionHandler conversionHandler)
        {

        }
    }
}