///////////////////////////////////////////////////////////
//  RoundDecorator.cs
//  Implementation of the Class RoundDecorator
//  Generated by Enterprise Architect
//  Created on:      20-Mar-2019 9:59:44 AM
///////////////////////////////////////////////////////////

using System;

namespace LengthConversionProgram
{ 
    public class RoundDecorator : HandlerDecorator
    {

        public RoundDecorator(ConversionHandler conversionHandler)
        {
            this.conversionHandler = conversionHandler;
            this.conversionHandler.DecoratedOutput =
                Math.Round(Double.Parse(this.conversionHandler.DecoratedOutput), 2).ToString();
        }

    }
}
