///////////////////////////////////////////////////////////
//  UnitDecorator.cs
//  Implementation of the Class UnitDecorator
//  Generated by Enterprise Architect
//  Created on:      20-Mar-2019 9:59:47 AM
///////////////////////////////////////////////////////////


namespace LengthConversionProgram
{
    public class UnitDecorator : HandlerDecorator
    {
        public UnitDecorator(ConversionHandler conversionHandler)
        {
            this.conversionHandler = conversionHandler;
            this.conversionHandler.DecoratedOutput =
                $"{this.conversionHandler.DecoratedOutput} {}"; 
        }
    }
}

//this.DecoratedOutput + $" {unitRequested}";